### PR TITLE
Ics

### PR DESCRIPTION
**Pull request by Xlythe**
I've pretty heavily modified the ICS calculator (Not quite sure what changed from ICS to JB - I started before that). You can quickly test it out here: https://play.google.com/store/apps/details?id=com.android2.calculator3

New features:
-History (as a dropdown)
-X,Y graphing
-Matrices
-Hexadecimal and Binary support

and a lot more. The package name changed so I could put it on the market.

I hope I'm doing this right. I'm not sure how I'm supposed to be sending my changes.

### CODE REVIEW

**Comment by cm-gerrit** [comment]
Hi there;

This is an automated reply, to let you know CyanogenMod doesn't merge pull
requests submitted directly to our github.com repositories.

You can submit your change requests through our public review system,
located at http://review.cyanogenmod.com/

That review system is an installation of Google's Gerrit code review.
If you've never interacted with Gerrit before, we also suggest you take
a look at http://wiki.cyanogenmod.com/wiki/Howto:_Gerrit

Thanks!

**Comment by rmcc** [comment]
Disregard the gerrit autoresponder, this many patches are just cleaner to merge directly. Thanks!

**Comment by eljef** [comment]
Is it ok with you (Do I have your permission) to pull this and squash the commits into a single patch that can be pushed through gerrit? There will of-course be preservation of history and credit.

**Comment by Xlythe** [comment]
That's fine with me. I'm just glad I managed to submit it - git and gerrit both confuse me.

**Comment by Xlythe** [comment]
I'm sure everyone's busy, but is there anything I need to fix or do differently?

**Comment by Xlythe** [comment]
I'm trying to figure out gerrit so I can submit the updates to my initial code. Do I have to download the entire Android source code just to submit a modification to the calculator?

**Comment by rmcc** [comment]
It's easier, but no. You can just use plain old git push, like _git push [URL] refs/for/[branchname]_ (the Calculator is at ssh://[youyrlogin]@r.cyanogenmod.com:29418/CyanogenMod/android_packages_apps_Calculator)

**Comment by Xlythe** [comment]
Woo! It took me 8 days, but I'm almost making progress!

I did
-git clone ssh://Xlythe@r.cyanogenmod.com:29418/CyanogenMod/android_packages_apps_Calculator
-updated source to include changes
-git push

But I get the error 

"! [remote rejected] jellybean -> jellybean (can not update the reference as a fast forward) 
error: failed to push some refs to 'ssh://Xlythe@r.cyanogenmod.com:29418/CyanogenMod/android_packages_apps_Calculator'"

The same error pops up when I do
-git push ssh://Xlythe@r.cyanogenmod.com:29418/CyanogenMod/android_packages_apps_Calculator jellybean

**Comment by Xlythe** [comment]
Ah! I got it, I got it, I got it! I was missing "HEAD:refs/for/"

**Pull request closed without merging**
